// Copyright (c) 2026 John Suykerbuyk and SykeTech LTD
// SPDX-License-Identifier: MIT OR Apache-2.0

package testutil

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// BuildMeetingsFixture populates a fresh `meetings/` subtree under
// t.TempDir() with three meeting subdirectories and returns the
// absolute path to the `meetings/` root. The three meetings mirror the
// existing testdata fixtures:
//
//   - 2026-03-15_14-30 — uses meeting_full.md (rich actions)
//   - 2026-03-20_09-00 — uses meeting_simple.md
//   - 2026-03-22_10-00 — uses meeting_no_actions.md
//
// Each subdir contains:
//
//   - Meeting_<date>_<time>.md     (the note — `Meeting_` prefix is required
//     by meetingdata.findMDFiles for discovery via SearchNotes / etc.)
//   - audio_<date>_<time>.wav.json (minimal sidecar metadata)
//   - speakers.json                (copy of testdata/speakers.json)
//
// Tests requiring multiple isolated fixture sets simply call this
// once per test against their own t.TempDir().
func BuildMeetingsFixture(t *testing.T) string {
	t.Helper()
	root := filepath.Join(t.TempDir(), "meetings")
	if err := os.MkdirAll(root, 0o755); err != nil {
		t.Fatalf("BuildMeetingsFixture: mkdir %s: %v", root, err)
	}

	testdataDir, err := findTestdataDir()
	if err != nil {
		t.Fatalf("BuildMeetingsFixture: %v", err)
	}

	speakersJSON, err := os.ReadFile(filepath.Join(testdataDir, "speakers.json"))
	if err != nil {
		t.Fatalf("BuildMeetingsFixture: read speakers.json: %v", err)
	}

	type meeting struct {
		dirName  string
		noteFile string
		dateISO  string
		timeHHMM string
	}
	meetings := []meeting{
		{"2026-03-15_14-30", "meeting_full.md", "2026-03-15", "14-30"},
		{"2026-03-20_09-00", "meeting_simple.md", "2026-03-20", "09-00"},
		{"2026-03-22_10-00", "meeting_no_actions.md", "2026-03-22", "10-00"},
	}

	for _, m := range meetings {
		dir := filepath.Join(root, m.dirName)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatalf("BuildMeetingsFixture: mkdir %s: %v", dir, err)
		}

		// Note .md
		src := filepath.Join(testdataDir, m.noteFile)
		content, err := os.ReadFile(src)
		if err != nil {
			t.Fatalf("BuildMeetingsFixture: read %s: %v", src, err)
		}
		notePath := filepath.Join(dir, "Meeting_"+m.dirName+".md")
		if err := os.WriteFile(notePath, content, 0o644); err != nil {
			t.Fatalf("BuildMeetingsFixture: write %s: %v", notePath, err)
		}

		// Audio sidecar JSON (minimal but valid)
		sidecar := fmt.Sprintf(`{
  "audio_file": "audio_%s_%s.wav",
  "duration_sec": 900.0,
  "sample_rate": 16000,
  "channels": 1,
  "date": "%s",
  "time": "%s"
}
`, m.dateISO, m.timeHHMM, m.dateISO, strings.ReplaceAll(m.timeHHMM, "-", ":"))
		sidecarPath := filepath.Join(dir, fmt.Sprintf("audio_%s_%s.wav.json", m.dateISO, m.timeHHMM))
		if err := os.WriteFile(sidecarPath, []byte(sidecar), 0o644); err != nil {
			t.Fatalf("BuildMeetingsFixture: write sidecar %s: %v", sidecarPath, err)
		}

		// speakers.json
		speakersPath := filepath.Join(dir, "speakers.json")
		if err := os.WriteFile(speakersPath, speakersJSON, 0o644); err != nil {
			t.Fatalf("BuildMeetingsFixture: write speakers.json: %v", err)
		}
	}

	return root
}

// CopyNoteFixture copies one of the canonical meeting note fixtures
// (`meeting_full`, `meeting_simple`, `meeting_no_actions`) from the
// shared testdata directory into a fresh t.TempDir() and returns the
// absolute destination path. The `.md` extension is added automatically.
func CopyNoteFixture(t *testing.T, name string) string {
	t.Helper()
	if !strings.HasSuffix(name, ".md") {
		name = name + ".md"
	}
	testdataDir, err := findTestdataDir()
	if err != nil {
		t.Fatalf("CopyNoteFixture: %v", err)
	}
	src := filepath.Join(testdataDir, name)
	content, err := os.ReadFile(src)
	if err != nil {
		t.Fatalf("CopyNoteFixture: read %s: %v", src, err)
	}
	dst := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(dst, content, 0o644); err != nil {
		t.Fatalf("CopyNoteFixture: write %s: %v", dst, err)
	}
	return dst
}

// WriteTempConfig serializes cfg as a hand-rolled YAML document and
// writes it to t.TempDir()/config.yaml, returning the path. The format
// matches what meetingdata.LoadConfig's parseYAML expects: two-level
// nesting via indentation, plain `key: value` pairs at each level.
//
// Sections (keys whose value is a map) are emitted with the section
// name as a bare key followed by indented child entries. Sections are
// emitted in sorted order for determinism. Values are written as bare
// strings except when they need quoting (contain `:` or leading
// whitespace); the meetingdata parser strips matched quotes.
func WriteTempConfig(t *testing.T, cfg map[string]any) string {
	t.Helper()
	dst := filepath.Join(t.TempDir(), "config.yaml")
	var sb strings.Builder
	sb.WriteString("# generated by testutil.WriteTempConfig\n")

	keys := make([]string, 0, len(cfg))
	for k := range cfg {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		v := cfg[k]
		switch vv := v.(type) {
		case map[string]any:
			fmt.Fprintf(&sb, "%s:\n", k)
			subKeys := make([]string, 0, len(vv))
			for sk := range vv {
				subKeys = append(subKeys, sk)
			}
			sort.Strings(subKeys)
			for _, sk := range subKeys {
				fmt.Fprintf(&sb, "  %s: %s\n", sk, yamlScalar(vv[sk]))
			}
		default:
			fmt.Fprintf(&sb, "%s: %s\n", k, yamlScalar(v))
		}
	}

	if err := os.WriteFile(dst, []byte(sb.String()), 0o644); err != nil {
		t.Fatalf("WriteTempConfig: write %s: %v", dst, err)
	}
	return dst
}

func yamlScalar(v any) string {
	s := fmt.Sprintf("%v", v)
	// Quote anything containing a colon (would confuse parseYAML) or
	// leading/trailing whitespace.
	if strings.ContainsAny(s, ":#") || strings.TrimSpace(s) != s {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}

// AgendaHTMLFixture writes a small (~1 KB) sample HTML agenda to
// t.TempDir()/agenda.html and returns the absolute path. The content
// is deliberately mundane — a Q2 planning skeleton — so tests that
// drive `web_fetch` against a `file://` URL or scripted server can
// assert on extracted topic strings.
func AgendaHTMLFixture(t *testing.T) string {
	t.Helper()
	dst := filepath.Join(t.TempDir(), "agenda.html")
	const body = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Q2 Planning Agenda</title>
</head>
<body>
  <h1>Q2 Planning</h1>
  <p>Quarterly planning kickoff for the engineering team.</p>
  <h2>Topics</h2>
  <ul>
    <li>Topic A: Backend migration retrospective</li>
    <li>Topic B: Frontend integration sequencing</li>
    <li>Topic C: Tooling investments for Q2</li>
    <li>Topic D: Hiring updates and onboarding rotations</li>
  </ul>
  <h2>Participants</h2>
  <ul>
    <li>Alice Smith (eng lead)</li>
    <li>Bob Jones (backend)</li>
    <li>Charlie Brown (frontend)</li>
  </ul>
  <h2>Notes</h2>
  <p>Bring updates from your sub-team. Aim for a 60-minute discussion
  with a 15-minute summary at the end. Action items will be filed in
  the team tracker after the meeting.</p>
</body>
</html>
`
	if err := os.WriteFile(dst, []byte(body), 0o644); err != nil {
		t.Fatalf("AgendaHTMLFixture: write %s: %v", dst, err)
	}
	return dst
}

// findTestdataDir locates `tools/meetingdata/testdata/` relative to
// the module root. Reuses findModuleRoot from binary.go.
func findTestdataDir() (string, error) {
	moduleRoot, err := findModuleRoot()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(moduleRoot, "meetingdata", "testdata")
	if _, err := os.Stat(dir); err != nil {
		return "", fmt.Errorf("findTestdataDir: %s: %w", dir, err)
	}
	return dir, nil
}
