# Copyright (c) 2026 John Suykerbuyk and SykeTech LTD
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Phase E.6.2 — pure-CMake asset embedder.
#
# Reads each input file's bytes, emits a single C++ header at OUTPUT
# declaring `static constexpr unsigned char <name>_bytes[]`,
# `static constexpr size_t <name>_len`, and `static constexpr const
# char* <name>_content_type` for each asset. No external tool
# dependency (no xxd, no Perl, no Python — pure CMake `file(READ HEX)`).
#
# Usage (driven from a parent CMakeLists.txt via add_custom_command):
#
#   cmake \
#       -DASSETS=<src1>;<src2>;... \
#       -DNAMES=<name1>;<name2>;... \
#       -DCONTENT_TYPES=<ct1>;<ct2>;... \
#       -DOUTPUT=<path/to/web_assets.h> \
#       -DNAMESPACE=recmeet::web_assets \
#       -P cmake/embed_assets.cmake
#
# The three list arguments must be the same length. NAMES become the
# C++ identifier roots (no extension, no dots — caller is responsible).

if(NOT DEFINED ASSETS)
    message(FATAL_ERROR "embed_assets.cmake: -DASSETS=<list> is required")
endif()
if(NOT DEFINED NAMES)
    message(FATAL_ERROR "embed_assets.cmake: -DNAMES=<list> is required")
endif()
if(NOT DEFINED CONTENT_TYPES)
    message(FATAL_ERROR "embed_assets.cmake: -DCONTENT_TYPES=<list> is required")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_assets.cmake: -DOUTPUT=<path> is required")
endif()
if(NOT DEFINED NAMESPACE)
    set(NAMESPACE "recmeet::web_assets")
endif()

list(LENGTH ASSETS _n_assets)
list(LENGTH NAMES _n_names)
list(LENGTH CONTENT_TYPES _n_cts)
if(NOT _n_assets EQUAL _n_names OR NOT _n_assets EQUAL _n_cts)
    message(FATAL_ERROR
        "embed_assets.cmake: ASSETS / NAMES / CONTENT_TYPES list lengths "
        "must match (got ${_n_assets} / ${_n_names} / ${_n_cts})")
endif()

# Split namespace string `a::b::c` into nested namespace open / close lines.
string(REPLACE "::" ";" _ns_parts "${NAMESPACE}")
set(_ns_open  "")
set(_ns_close "")
foreach(_p IN LISTS _ns_parts)
    set(_ns_open  "${_ns_open}namespace ${_p} {\n")
    set(_ns_close "} // namespace ${_p}\n${_ns_close}")
endforeach()

set(_body "// AUTO-GENERATED by cmake/embed_assets.cmake — DO NOT EDIT.\n")
string(APPEND _body "// Phase E.6.2 — recmeet-tray embedded WebUI asset bundle.\n")
string(APPEND _body "//\n")
string(APPEND _body "// Each asset is exposed as a flat byte array + length + content type.\n")
string(APPEND _body "// Served verbatim by tray_web.cpp's static-asset handlers.\n")
string(APPEND _body "\n")
string(APPEND _body "#pragma once\n")
string(APPEND _body "\n")
string(APPEND _body "#include <cstddef>\n")
string(APPEND _body "\n")
string(APPEND _body "${_ns_open}")
string(APPEND _body "\n")

math(EXPR _last "${_n_assets} - 1")
foreach(_i RANGE 0 ${_last})
    list(GET ASSETS ${_i} _src)
    list(GET NAMES ${_i} _name)
    list(GET CONTENT_TYPES ${_i} _ct)

    if(NOT EXISTS "${_src}")
        message(FATAL_ERROR "embed_assets.cmake: asset not found: ${_src}")
    endif()

    file(READ "${_src}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _byte_len "${_hex_len} / 2")

    string(APPEND _body "// ----- ${_name}: ${_src} (${_byte_len} bytes) -----\n")
    string(APPEND _body "static constexpr const char* ${_name}_content_type = \"${_ct}\";\n")
    string(APPEND _body "static constexpr std::size_t ${_name}_len = ${_byte_len};\n")
    string(APPEND _body "static constexpr unsigned char ${_name}_bytes[${_byte_len} + 1] = {\n  ")

    # Walk the hex string two characters at a time, emit `0xHH, ` with a
    # newline every 16 bytes to keep diff churn local on regen and stay
    # under any compiler line-length sanity limits.
    set(_col 0)
    set(_pos 0)
    while(_pos LESS _hex_len)
        string(SUBSTRING "${_hex}" ${_pos} 2 _hh)
        string(APPEND _body "0x${_hh}, ")
        math(EXPR _pos "${_pos} + 2")
        math(EXPR _col "${_col} + 1")
        if(_col EQUAL 16)
            string(APPEND _body "\n  ")
            set(_col 0)
        endif()
    endwhile()
    # Trailing 0x00 sentinel makes the buffer usable as a C-string for
    # text assets without copying. Not relied on by the byte-array consumers.
    string(APPEND _body "0x00\n};\n\n")
endforeach()

string(APPEND _body "${_ns_close}")

# Atomic write: write through a side file then rename so a parallel
# build never sees a half-written header.
set(_tmp "${OUTPUT}.tmp")
get_filename_component(_outdir "${OUTPUT}" DIRECTORY)
if(_outdir)
    file(MAKE_DIRECTORY "${_outdir}")
endif()
file(WRITE "${_tmp}" "${_body}")
file(RENAME "${_tmp}" "${OUTPUT}")
